# Generated by Django 5.2.8 on 2025-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPMNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='bpmn/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tasks', models.JSONField(blank=True, null=True)),
                ('events', models.JSONField(blank=True, null=True)),
                ('gateways', models.JSONField(blank=True, null=True)),
                ('flows', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
